---
- hosts: bot
  tasks:
    - name: Клонирование репозитория и checkout в ветку ansible
      git:
        repo: https://github.com/Ivanich41/START
        dest: /home/vagrant/START
        version: ansible
        update: yes

    - name: Установка зависимостей из requirements.txt
      pip:
        requirements: /home/vagrant/START/requirements.txt
        state: present

    - name: Копирование .env файла с контроллера на удалённый хост
      copy:
        src: /home/vagrant/.env
        dest: /home/vagrant/START/.env
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Запуск main.py в nohup
      command: nohup python3 /home/vagrant/START/main.py &
      args:
        chdir: /home/vagrant/START
        creates: /tmp/start.lock
      async: 1
      poll: 0

- hosts: primary
  become: True
  tasks:
    - name: Копирование postgresql.conf
      copy:
        src: /home/vagrant/pg_configs/primary/postgresql.conf
        dest: /etc/postgresql/14/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Копирование pg_hba.conf
      copy:
        src: /home/vagrant/pg_configs/primary/pg_hba.conf
        dest: /etc/postgresql/14/main/pg_hba.conf
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Перезапуск службы postgresql
      service:
        name: postgresql
        state: restarted

    - name: Создание базы данных homework
      become: yes
      become_user: postgres
      postgresql_db:
        name: homework
        state: present
        login_user: postgres

    - name: Загрузка схемы из файла schema.sql
      become: yes
      become_user: postgres
      command: psql homework -f /vagrant/schema.sql

- hosts: replica
  become: True
  tasks:
    - name: Копирование postgresql.conf для реплики
      copy:
        src: /vagrant/pg_configs/replica/postgresql.conf
        dest: /etc/postgresql/14/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Остановка службы postgresql
      service:
        name: postgresql
        state: stopped

    - name: Удаление данных в директории main
      file:
        path: /var/lib/postgresql/14/main/
        state: absent

    - name: Запуск службы postgresql после очистки
      service:
        name: postgresql
        state: started

    - name: Выполнение pg_basebackup
      become: yes
      become_user: postgres
      command: pg_basebackup -R -h 192.168.50.11 -U repl_user -D /var/lib/postgresql/14/main -P
      environment:
        PGPASSWORD: "111"
      register: pg_basebackup_result
      failed_when: pg_basebackup_result.rc != 0
      changed_when: False